language: node_js
node_js: node
services:
- mongodb
env:
  global:
    secure: rKjAlQRfBracPKAIDd1nDsdG6w1nO0fWuBSqtHKRt9n+2VAftF9Cgi2YpnabqcwZRpHWFaR/WuaKxaBjdCrJQbj8gUDHn8U6RUdQnELa84Ix3STbXo18DiepNg4o+LnsHxqak3yJNtCJKu0YxwQ7h55w5qk3M84An9hIaq1tqoEPkVRF9Xixh3jFfvNbjRlbyKFlkHzXtfQKx3eynCC0acBVs/APOioVd5ollm+iwtzRSoZAS4qAeY0O2PAZdBMBsLd+z28CqZsCzu0wkkJRNLokzQS6A3H0WRyXOKvRdNzfZniPmcLAa+F30txnx2qnYocThkcJ1j6pwqJBZpF0GbjSbwHByqi+ENxj6DRaOBRLEYGFNiWLgFSByczlSYyNHWvewYyedi15oE31hy4Z0VCVC3anktOaOOgrUAd2Ai1L/KhKaq8H+AmsPALkbd2JCGBt6lEQolvkP/QXDeaXBpsLHT8qknp5M9IDaa4ibOxE6JObx1DgEEutaW0s2c+efUD3HjE6HLr5PaYtEQzdfcDaZqMbHHYPg5DIxkVushskFxcmrb6/JnrVz9l4SV+uF2Y0NXJ5b0eXOWqRkHMcaSQKrRswfGQlbWKeGYwK0fyP0FnX6o4QXeEx95zTduPYBebkgt2xebYbpMAtY7RZqX3eSkc9C+TjIFwnB0mSpHM=
